%include "colon.inc"
section .rodata

colon "long_key_______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________", element4
db "value_of_long_key", 0

colon "key3", element3
db "value3", 0

colon "key2", element2
db "value2", 0

colon "key1", element1
db "value1", 0
